# Ultra Stellar <ultrastellar.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="UltraStellar"
ORG_URL="https://ultrastellar.github.io/"
ORG_LOGO = ""
ORG_OFFICIAL_EMAIL=""
ORG_SUPPORT_EMAIL=""
ORG_TWITTER=""
ORG_DESCRIPTION=""

[[CURRENCIES]]
code = ""
name = ""
issuer = ""
is_asset_anchored = false
display_decimals = 7
desc=""
image=""
conditions=""
